version: '3.3'

services:
  mysqldb:
    container_name: sepotipayi-rest-db
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: $MYSQLDB_DATABASE
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
  app:
    container_name: sepotipayi-rest-service
    restart: unless-stopped
    depends_on:
      - mysqldb
    build: 
      context: .
      dockerfile: Dockerfile
    env_file: ./.env 
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
      - JWT_SECRET_KEY=$JWT_SECRET_KEY
      - JWT_EXPIRE=$JWT_EXPIRE
      - PORT=$NODE_DOCKER_PORT
      - SOAP_PORT=$SOAP_PORT
      - APP_PORT=$APP_PORT
      - PREMIUM_APP_PORT=$PREMIUM_APP_PORT
      - API_KEY=$API_KEY
    stdin_open: true
    tty: true

volumes:
  db: